try {
    console.log(naoExisto)
} catch(err) {
    console.log("NÃ£o existe isso")
    console.log(err);
}